debug = false
random_seed = 0xc61dd8fc

[data]
num_features = 1
num_samples = 50
sigma_noise = 0.1

[training]
batch_size = 64
num_iters = 11700 # 50000 training images / 64 * 15, rounded down
learning_rate = 0.001

[plotting]
output_dir = "artifacts"
figsize = [5, 3]
dpi = 200
