# pyproject.toml.jinja

[project]
name = "example"
version = "0.1.0"
description = "Example of linear regression"
readme = "README.md"
authors = [
    { name = "ECE472 Course Staff", email = "noreply@cooper.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "structlog",
    "rich",
    "numpy",
    "pydantic",
    "pydantic-settings>=2.10.1",
    "matplotlib>=3.10.5",
    "tqdm>=4.67.1",
    "jax[cpu,cuda12]>=0.7.1",
    "flax>=0.11.2",
    "optax>=0.2.4",
    "scikit-learn",
    "libtpu>=0.0.47",
]

[project.scripts]
example = "example:main"
example-evaluate = "example.evaluate:main"
[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

