debug = false
random_seed = 0xc61dd8fc

[data]
num_features = 1
num_samples = 50
sigma_noise = 0.1

[training]
batch_size = 64
num_iters = 4500 # less than 5 epochs
learning_rate = 0.1

[plotting]
output_dir = "artifacts"
figsize = [5, 3]
dpi = 200
